### ISSUE TITLE
Got this error

### ISSUE THREAD

**Issue by darrellweaverjr** [kushgps/api#1]
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by darrellweaverjr** [comment]
I  updated node and got this now

D:\kushgps\api\server.js:33
  Dispensary.find({}, (err, dispensaries) => {
                                          ^^
SyntaxError: Unexpected token =>
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3

**Comment by SapioBeasley** [comment]
In CLI run `node -v` make sure it's v4.7.2 anf higher. It's complaining about the es6 compatability
